project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Remotely Sensing Cities and Environments"
  author: "James Nutthaphol Rakratchatakul"
  date: "1/19/2023"
  navbar:
    logo: images/casa_logo.jpg
    collapse: true
    collapse-below: lg
    background: dark
    search: true
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    
editor: visual

